import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import "../assets/styles/globals.scss";

const workSans = Work_Sans({
  subsets: ["latin"],
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={workSans.className}>{children}</body>
    </html>
  );
}
